# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cw2JQlKP3EJ_3lLn6cK87tRm2C3_wp23
"""

import pandas as pd
df = pd.read_csv('Bookings.csv')
df

df.isnull().sum()

df.dropna(subset=['Review'], inplace=True)

print(df)

df.isnull().sum()

unique_values = df['Review'].unique()
print(unique_values)  # Output: [1 2 3]

#Hugging Face Transformer
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Define candidate labels for classification
candidate_labels = ["Very positive", "Positive"]

# Perform Zero-Shot Classification on the Review column
def classify_review(text):
    try:
        result = classifier(text, candidate_labels)
        return result['labels'][0]  # Return the label with the highest confidence
    except Exception as e:
        return "Error"

# Apply classification to the Review column
df['Sentiment'] = df['Review'].apply(classify_review)

# Check the results
print(df[['Review', 'Sentiment']])

sentiment_counts = df['Sentiment'].value_counts()
print(sentiment_counts)

import matplotlib.pyplot as plt
import seaborn as sns

# Plot pie chart for sentiment distribution
plt.figure(figsize=(8, 8))
sentiment_counts.plot.pie(autopct='%1.1f%%', colors=sns.color_palette('Set2'))
plt.title('Sentiment Distribution')
plt.ylabel('')
plt.show()

dummy_labels = np.random.choice(["Very positive", "Positive"], size=len(df))

import matplotlib.pyplot as plt

# Plot sentiment distribution
sentiment_counts = df['Sentiment'].value_counts()
plt.figure(figsize=(8, 6))
sentiment_counts.plot(kind='bar', color=['skyblue', 'salmon'])
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.show()

# Find the hotels with the highest number of reviews
most_reviewed_hotels = df.groupby('Hotel_Name')['Total_Review'].sum().sort_values(ascending=False)

# Display the top 10 most reviewed hotels
print(most_reviewed_hotels.head(10))

import seaborn as sns
import matplotlib.pyplot as plt

# Plot the distribution of ratings
plt.figure(figsize=(8, 6))
sns.histplot(df['Rating'], bins=10, kde=True, color='skyblue')
plt.title('Rating Distribution')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()